#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'runit', '~> 1.6.0'
cookbook 'nginx', '~> 2.7.6'
cookbook 'rbenv', '~> 1.7.1'
cookbook 'latest-git', :git => 'https://github.com/aspyatkin/latest-git.git', :ref => 'v1.1.1'
cookbook 'latest-nodejs', :git => 'https://github.com/aspyatkin/latest-nodejs.git', :ref => 'v1.1.1'
cookbook 'dotfiles-cookbook', :git => 'https://github.com/aspyatkin/dotfiles-cookbook.git', :ref => 'v1.1.0'
